[package]
name = "pomodoro"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
strum = "0.26.3"
tokio = {version="1", features = ["full"]}
tokio-util = "0.7.13"
